spring:
  datasource:
    url: jdbc:mysql://localhost/forum
    username: forum
    password: forum
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:h2:mem:forum
#    username: forum
#    password: forum
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

#  h2:
#    console:
#      path: /h2
#      enabled: true

server:
  port: 80
